### ISSUE TITLE
Examples in lessons related to objects in L6

### ISSUE THREAD

**Issue by reenas** [pupilfirst/web-development-101-script#35]
The examples used in lessons related to objects starting from [numbers-booleans-objects/creating-and-working-with-objects](https://github.com/pupilfirst/web-development-101-script/tree/v2/numbers-booleans-objects/creating-and-working-with-objects) are very different/random - like cars, computer in this one and employee in the [numbers-booleans-objects/add-update-delete-objects](https://github.com/pupilfirst/web-development-101-script/tree/v2/numbers-booleans-objects/add-update-delete-objects) lesson. 

The set of examples should be related to the L8 project if possible and if not at all possible, at least based on a common theme/use case/scenario.

**Comment by reenas** [comment]
@avishekjana I am unable to find who reviewed these set of lessons?

**Comment by avishekjana** [comment]
@reenas Melson reviewed it, 
here is the PR link: https://github.com/pupilfirst/web-development-101-script/pull/16

**Comment by reenas** [comment]
Okay @avishekjana, please address the issue I have mentioned in the lessons and get it checked by @mjzac. I will have a look then.
