### ISSUE TITLE
Introduction to HTML Elements

### ISSUE THREAD

**Issue by reenas** [pupilfirst/web-development-101-script#60]

**Comment by mjzac** [comment]
@reenas I have uploaded the video here https://drive.google.com/drive/folders/1hGpi_vLJmRI0XFE8_Jp9KfMU0zB1Q3cq?usp=sharing

**Comment by reenas** [comment]
@mjzac This video can be improved, in general, in terms of energy of delivery and discontinuity where there are long pauses or fillers like ummm etc. Also, the jump from `Form` element to `Table` element could have been smoothened by going back to the documentation and then moving to the documentation related to table, so it's clear that we are referring to the same Mozilla documentation. 

I think, a little more practice should improve this and make the video a little more tight. This is food for thought for future videos you do. You can close this once you have seen.

**Comment by reenas** [comment]
This video has been updated on LMS and previous comment considered for later videos.
