### ISSUE TITLE
CSS Styling Overrides

### ISSUE THREAD

**Issue by reenas** [pupilfirst/web-development-101-script#65]

**Comment by avishekjana** [comment]
@reenas @harigopal Please review the recording once.
https://drive.google.com/file/d/1_FrDkFU8fbu2wnqp76FeiskJU2cthC8o/view?usp=sharing

**Comment by reenas** [comment]
@avishekjana The first part - cascading order in the video was spoken without any example on screen. 
Inheritance was covered in much detail and is clear.

**Comment by reenas** [comment]
Closing this issue as the video was updated. The updated video is available on LMS.
