### ISSUE TITLE
Creating and working with Objects

### ISSUE THREAD

**Issue by reenas** [pupilfirst/web-development-101-script#68]

**Comment by avishekjana** [comment]
@reenas @harigopal Please review the video: https://drive.google.com/file/d/1pjyROOG1YcWk8hNWKn_JVqbwwTXx20Z1/view?usp=sharing

**Comment by reenas** [comment]
@avishekjana This video seems fine overall. 

**One input** - We ask students to give meaningful names always, hence instead of calling objects as u1, u2, it would be much better to name them as user1, user2.

**Comment by avishekjana** [comment]
ok, noted.
