### ISSUE TITLE
Manipulating Objects

### ISSUE THREAD

**Issue by reenas** [pupilfirst/web-development-101-script#71]

**Comment by avishekjana** [comment]
@reenas @harigopal Please check the recording of the lesson: https://drive.google.com/file/d/1ueijywv024Oks3WyIu8lgTioQ15aXhYO/view?usp=sharing

**Comment by reenas** [comment]
@avishekjana 
- Minor typo at 3:26 - it says JavScript instead of JavaScript
- Since the lessons are in sequence, it is better if examples are also consistent. The definition of user object in previous video on accessing properties is different from what you have shown here. Taking examples done in a previous lesson and improving on that to teach something new in the current lesson, helps students understand concepts in a flow, and they can also easily practice you are teaching with the example they have build until now.

Again, these are food for thought for future videos.

**Comment by avishekjana** [comment]
OK, Noted.
