### ISSUE TITLE
Creating Validations

### ISSUE THREAD

**Issue by reenas** [pupilfirst/web-development-101-script#76]

**Comment by vikispeaks** [comment]
@reenas This was already created as text. Excel is updated with the confirmation.

**Comment by reenas** [comment]
@vikispeaks Okay, I have seen the text. In my opinion, this lesson needs a video as it is reasonably complex for a beginner course. Validations are important and having it simply as text may not help all students understand and appreciate it properly. Can you work on creating a video for it? 

You can start with a form where you briefly skim through the elements for a min and then go deep into adding validations.
